os: Visual Studio 2015

environment:
  matrix:
    - nodejs_version: 4
    - nodejs_version: 6
    - nodejs_version: 8

platform:
  - x64
  - x86

shallow_clone: true

install:
  - ps: Install-Product node $env:nodejs_version $env:Platform
  - ps: Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force
  - npm config get
  # upgrade node-gyp to dodge 2013 compile issue present in the node gyp bundled with node v0.10
  - npm install npm@5 -g
  - npm install node-gyp
  - IF "%nodejs_version:~0,1%"=="0" npm install node-gyp@3.x
  # upgrade node-gyp to dodge https://github.com/mapbox/node-pre-gyp/issues/209#issuecomment-307641388
  # and allow make node 4.x x86 builds work
  # https://github.com/mapbox/node-pre-gyp/issues/209#issuecomment-217690537
  - IF "%nodejs_version:~0,1%"=="4" npm install node-gyp@3.x
  - node --version
  - npm --version
  - node -e "console.log(process.arch);"
  - IF /I "%PLATFORM%" == "x64" set PATH=C:\Python27-x64;%PATH%
  - IF /I "%PLATFORM%" == "x86" SET PATH=C:\python27;%PATH%
  - IF /I "%PLATFORM%" == "x64" CALL "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - IF /I "%PLATFORM%" == "x86" CALL "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - npm install
  - npm install npm@2 -g
  - npm test

build: off
test: off
deploy: off
